services:
  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../src:/app/src
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:17
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

volumes:
  postgres_data:
